/*
 * Tetris — the catalogue's falling-block classic. One player (solo, or watch the
 * computer), or two players side-by-side on one screen (versus, with garbage).
 * Touch-first, gesture-driven, with a little keyboard support for desktop dev.
 *
 * Mirrors the catalogue's conventions (see games/gomoku/gomoku.js):
 *   - classic script, no modules, runs from file:// (everything under window.NG).
 *   - the three design ratios via NG.classify / NG.onResize. Tetris uses the
 *     fixed-ratio LETTERBOX strategy: each well is a 10x20 grid, so we size a
 *     square cell that fits and centre the well(s), keeping cells square in 16:9,
 *     9:8 and 9:16 alike. The leftover space hosts the chrome (NEXT / HOLD /
 *     score panels in landscape, bands above the well in portrait).
 *   - a robot icon per player toggles that side between YOU and COMPUTER, so
 *     solo, vs-computer and computer-vs-computer all fall out of the same wells.
 *
 * Touch controls (each finger drives the well it starts over):
 *   - drag left / right : slide the piece column by column (follows the finger)
 *   - tap               : rotate clockwise
 *   - drag / flick down  : soft drop while held; a fast downward flick hard-drops
 *   - swipe up          : hold (swap the piece into the HOLD slot)
 *
 * Mechanics are classic and physically grounded (see the project memory on
 * "visible cause"): pieces come from a 7-bag so the sequence is fair; a ghost
 * shows exactly where the piece lands; line clears flash before they collapse;
 * and in 2-player, clearing 2+ lines drops real garbage rows into the opponent's
 * well, pushing their stack up toward the ceiling. The computer is a heuristic
 * placement player (aggregate height / holes / bumpiness / lines), and it MOVES
 * the piece across visibly before dropping — no teleporting.
 *
 * Pure board/piece functions live at the top (no DOM, unit-tested headlessly);
 * the NG.ready block wraps them in per-well game state, input and rendering.
 */
(function () {
  'use strict';

  // ===========================================================================
  // PURE CORE — board & piece maths. No DOM, no game state; everything takes a
  // flat board array (length COLS*ROWS; 0 = empty, else a colour string) plus
  // explicit piece cells. Unit-tested in Node before the UI is wired on top.
  // ===========================================================================
  var COLS = 10, ROWS = 20;

  // Classic-coloured pieces, tuned to the catalogue's neon-phosphor palette.
  var COLORS = {
    I: '#36dcff', O: '#ffcf4d', T: '#b46bff',
    S: '#4dff88', Z: '#ff5d6c', J: '#5b8cff', L: '#ff9f43',
  };
  var GARBAGE = '#5a6b62';
  var TYPES = ['I', 'O', 'T', 'S', 'Z', 'J', 'L'];

  // Base (spawn) shapes as [x,y] blocks inside an n x n box. The other three
  // rotations are generated by rotating clockwise: (x,y) -> (n-1-y, x).
  var BASE = {
    I: { n: 4, cells: [[0, 1], [1, 1], [2, 1], [3, 1]] },
    O: { n: 2, cells: [[0, 0], [1, 0], [0, 1], [1, 1]] },
    T: { n: 3, cells: [[1, 0], [0, 1], [1, 1], [2, 1]] },
    S: { n: 3, cells: [[1, 0], [2, 0], [0, 1], [1, 1]] },
    Z: { n: 3, cells: [[0, 0], [1, 0], [1, 1], [2, 1]] },
    J: { n: 3, cells: [[0, 0], [0, 1], [1, 1], [2, 1]] },
    L: { n: 3, cells: [[2, 0], [0, 1], [1, 1], [2, 1]] },
  };

  function rotateCW(cells, n) {
    var out = [];
    for (var i = 0; i < cells.length; i++) out.push([n - 1 - cells[i][1], cells[i][0]]);
    return out;
  }
  function minOf(cells, axis) {
    var m = Infinity;
    for (var i = 0; i < cells.length; i++) m = Math.min(m, cells[i][axis]);
    return m;
  }

  // SHAPES[type] = { n, color, spawnX, spawnY, rot: [cells0..cells3] }.
  // spawnX centres the box; spawnY lifts the piece so its topmost block sits on
  // row 0 (so nothing ever spawns at a negative row in the normal case).
  var SHAPES = {};
  (function buildShapes() {
    for (var t = 0; t < TYPES.length; t++) {
      var ty = TYPES[t], b = BASE[ty], rots = [b.cells];
      for (var r = 1; r < 4; r++) rots.push(rotateCW(rots[r - 1], b.n));
      SHAPES[ty] = {
        n: b.n, color: COLORS[ty], rot: rots,
        spawnX: Math.floor((COLS - b.n) / 2),
        spawnY: -minOf(b.cells, 1),
      };
    }
  })();

  // Kicks tried (in order) when a rotation collides — a pragmatic wall/floor kick
  // set: no shift first, then sideways, then nudge up. Good feel without the full
  // SRS tables (this catalogue doesn't need T-spin fidelity).
  var KICKS = [[0, 0], [-1, 0], [1, 0], [-2, 0], [2, 0], [0, -1], [-1, -1], [1, -1]];

  function collides(board, cells, px, py) {
    for (var i = 0; i < cells.length; i++) {
      var x = px + cells[i][0], y = py + cells[i][1];
      if (x < 0 || x >= COLS || y >= ROWS) return true;     // wall / floor
      if (y >= 0 && board[y * COLS + x]) return true;        // existing block
    }
    return false;
  }

  // Drop cells straight down from startY until they would collide; return the
  // resting y. (Caller ensures startY itself doesn't collide.)
  function dropY(board, cells, px, startY) {
    var y = startY;
    while (!collides(board, cells, px, y + 1)) y++;
    return y;
  }

  function stamp(board, cells, px, py, color) {
    for (var i = 0; i < cells.length; i++) {
      var x = px + cells[i][0], y = py + cells[i][1];
      if (y >= 0) board[y * COLS + x] = color;
    }
  }

  function fullRows(board) {
    var rows = [];
    for (var y = 0; y < ROWS; y++) {
      var full = true;
      for (var x = 0; x < COLS; x++) { if (!board[y * COLS + x]) { full = false; break; } }
      if (full) rows.push(y);
    }
    return rows;
  }

  // Return a new board with `rows` removed and empty rows pushed in at the top.
  function clearRows(board, rows) {
    var drop = {};
    for (var i = 0; i < rows.length; i++) drop[rows[i]] = true;
    var out = new Array(ROWS * COLS);
    for (var k = 0; k < out.length; k++) out[k] = 0;
    var wy = ROWS - 1;
    for (var y = ROWS - 1; y >= 0; y--) {
      if (drop[y]) continue;
      for (var x = 0; x < COLS; x++) out[wy * COLS + x] = board[y * COLS + x];
      wy--;
    }
    return out;
  }

  // Column heights / holes / bumpiness — the features the computer scores on.
  function boardMetrics(board) {
    var heights = new Array(COLS), holes = 0, x, y;
    for (x = 0; x < COLS; x++) {
      var h = 0, seen = false;
      for (y = 0; y < ROWS; y++) {
        if (board[y * COLS + x]) { if (!seen) { seen = true; h = ROWS - y; } }
        else if (seen) holes++;
      }
      heights[x] = h;
    }
    var agg = 0, bump = 0;
    for (x = 0; x < COLS; x++) {
      agg += heights[x];
      if (x < COLS - 1) bump += Math.abs(heights[x] - heights[x + 1]);
    }
    return { agg: agg, holes: holes, bump: bump, heights: heights };
  }

  // Weighted value of leaving the piece (cells at px,py) on this board — the
  // classic 4-feature heuristic (El-Tetris / Lee weights). Higher is better.
  var W_AGG = -0.510066, W_LINES = 0.760666, W_HOLES = -0.35663, W_BUMP = -0.184483;
  function evaluatePlacement(board, cells, px, py) {
    var b = board.slice();
    stamp(b, cells, px, py, 1);
    var rows = fullRows(b), lines = rows.length;
    if (lines) b = clearRows(b, rows);
    var m = boardMetrics(b);
    return W_AGG * m.agg + W_LINES * lines + W_HOLES * m.holes + W_BUMP * m.bump;
  }

  // Best (rotation, column) to drop `type` on `board`: try every orientation and
  // horizontal position, score the landing, keep the max. Returns {rot,px,py,s}.
  function bestPlacement(board, type) {
    var def = SHAPES[type], best = null;
    for (var r = 0; r < 4; r++) {
      var cells = def.rot[r];
      for (var px = -2; px <= COLS + 1; px++) {
        if (collides(board, cells, px, def.spawnY)) continue;   // blocked at the top
        var py = dropY(board, cells, px, def.spawnY);
        var s = evaluatePlacement(board, cells, px, py);
        if (!best || s > best.s) best = { s: s, rot: r, px: px, py: py };
      }
    }
    return best;
  }

  // --- HOLD-aware / Tetris-seeking evaluation (used by the computer) ----------
  // Clearing more lines at once is rewarded super-linearly, so a Tetris (4 lines)
  // is worth far more than four singles — the computer will go for big clears,
  // which in 2-player send the most garbage ("punish the opponent").
  var AI_CLEAR_REWARD = [0, 0.8, 2.0, 3.6, 9.0];   // normal play: clear what you can
  // While "building" (board clean & low with an I in reach) we instead DISCOURAGE
  // 1-3 line clears and richly reward a Tetris, so the computer banks four-line
  // clears (the biggest garbage hit) instead of nibbling singles. The negative
  // values roughly cancel the height-reduction the heuristic would otherwise love.
  var AI_BUILD_REWARD = [0, -6, -12, -18, 28];
  var AI_WELL_BONUS = 0.6;        // reward for keeping one clean edge well open for an I
  var AI_READY_BONUS = 5;         // reward per "Tetris-ready" row (full but for the well)
  var AI_BUILD_MAXH = 9;          // stop building (clear normally) once the stack reaches here

  // Rows that are filled in every column EXCEPT the well column — the rows a
  // vertical I would complete all at once for a Tetris.
  function tetrisReadyRows(b, wellCol) {
    var ready = 0;
    for (var y = 0; y < ROWS; y++) {
      if (b[y * COLS + wellCol]) continue;        // well must be open on this row
      var full = true;
      for (var x = 0; x < COLS; x++) { if (x !== wellCol && !b[y * COLS + x]) { full = false; break; } }
      if (full) ready++;
    }
    return ready;
  }

  // Depth of the lower edge column below the rest of the stack (a 1-wide well an
  // I-piece could later fill for a Tetris). Only counts a *single* low edge.
  function edgeWellDepth(h) {
    function depthAt(col) {
      var restMin = Infinity;
      for (var i = 0; i < COLS; i++) if (i !== col) restMin = Math.min(restMin, h[i]);
      return restMin - h[col];
    }
    return Math.max(depthAt(0), depthAt(COLS - 1));
  }

  // Value of leaving `cells` at (px,py). Like evaluatePlacement, but with the
  // super-linear clear reward and — when an I is in reach (`iNear`) and the board
  // is clean and not too tall — a bonus for keeping an edge well open to set up a
  // Tetris. The clean/short gate stops it stacking into the danger zone.
  function aiPlacementValue(board, cells, px, py, iNear) {
    var b = board.slice();
    stamp(b, cells, px, py, 1);
    var rows = fullRows(b), lines = rows.length;
    if (lines) b = clearRows(b, rows);
    var m = boardMetrics(b);
    var hmax = 0;
    for (var i = 0; i < COLS; i++) if (m.heights[i] > hmax) hmax = m.heights[i];
    var s = W_AGG * m.agg + W_HOLES * m.holes + W_BUMP * m.bump;
    // Build toward a Tetris only while the board is clean and low and an I is near;
    // otherwise just clear lines to stay alive.
    var building = iNear && m.holes <= 1 && hmax <= AI_BUILD_MAXH;
    if (building) {
      var wellCol = m.heights[0] <= m.heights[COLS - 1] ? 0 : COLS - 1;
      s += AI_BUILD_REWARD[lines];
      s += AI_READY_BONUS * Math.min(tetrisReadyRows(b, wellCol), 4);   // stack rows the I will clear
      s += AI_WELL_BONUS * Math.min(edgeWellDepth(m.heights), 8);
    } else {
      s += AI_CLEAR_REWARD[lines];
    }
    return s;
  }

  function bestPlacementAI(board, type, iNear) {
    var def = SHAPES[type], best = null;
    for (var r = 0; r < 4; r++) {
      var cells = def.rot[r];
      for (var px = -2; px <= COLS + 1; px++) {
        if (collides(board, cells, px, def.spawnY)) continue;
        var py = dropY(board, cells, px, def.spawnY);
        var s = aiPlacementValue(board, cells, px, py, iNear);
        if (!best || s > best.s) best = { s: s, rot: r, px: px, py: py };
      }
    }
    return best;
  }

  // 7-bag randomiser: each bag is a shuffled permutation of all seven pieces, so
  // droughts and floods are impossible — the same fairness as modern Tetris.
  function makeBag() {
    var bag = TYPES.slice();
    for (var i = bag.length - 1; i > 0; i--) {
      var j = Math.floor(Math.random() * (i + 1));
      var tmp = bag[i]; bag[i] = bag[j]; bag[j] = tmp;
    }
    return bag;
  }

  // ===========================================================================
  // GAME — per-well state, layout, input, rendering. Wraps the pure core above.
  // ===========================================================================
  NG.ready(function () {
    var canvas = document.getElementById('game');
    var ctx = canvas.getContext('2d');

    // ---- palette ----------------------------------------------------------
    var FG = '#4dff88', DIM = '#1d5e38', INK = '#d6f7e4', MUTED = '#6b7a72';
    var WELL_BG = '#070b09', GRID = 'rgba(77,255,136,0.07)';

    // ---- tuning -----------------------------------------------------------
    var LOCK_DELAY = 0.5;          // s a grounded piece waits before it locks
    var MAX_LOCK_RESETS = 15;      // cap move/rotate lock-delay resets (anti-stall)
    var SOFT_MULT = 2;             // soft drop falls this many times normal speed (gentle)
    var CLEAR_TIME = 0.18;         // s the line-clear flash plays before collapsing
    var AI_STEP = 0.06;            // s between the computer's visible micro-moves
    var AI_HOLD_MARGIN = 0.4;      // how much better the held piece must score before the computer swaps
    var AI_SOFT_INTERVAL = 0.08;   // vs a human: cap the computer's soft descent here (s/row) so it
                                   // plays at a fair, beatable pace (~2s/piece) — never an instant slam
    var GARBAGE_FOR = [0, 0, 1, 2, 4];  // rows sent for clearing 1..4 lines

    function gravityInterval(level) { return Math.max(0.05, 0.8 * Math.pow(0.85, level - 1)); }
    function clamp(v, lo, hi) { return v < lo ? lo : v > hi ? hi : v; }
    function now() { return (window.performance && performance.now) ? performance.now() : Date.now(); }

    // ---- viewport / layout ------------------------------------------------
    var vw = 0, vh = 0, drawScale = 1, cell = 24;
    var hudMode = 'topBand';       // 'topBand' (portrait) | 'leftStack' (1P land.) | 'sideEach' (2P land.)
    var wellRects = [];            // {x,y,w,h} per active well

    // ---- game state -------------------------------------------------------
    var state = 'menu';            // 'menu' | 'playing' | 'over'
    var paused = false;            // PAUSE freezes play (only meaningful while playing)
    var numPlayers = 1;
    var wells = [];
    var result = null;             // {solo:true} | {winner: playerNo}
    var clock = 0;                 // wall clock for pulses / flashes
    var ptrs = Object.create(null);// pointer id -> gesture tracker

    function otherWell(w) { return w === wells[0] ? wells[1] : wells[0]; }

    function makeWell(player) {
      return {
        player: player,
        board: newBoard(),
        bag: [], queue: [],
        type: null, rot: 0, px: 0, py: 0,
        hold: null, canHold: true,
        score: 0, lines: 0, level: 1,
        dead: false,
        gravity: 0, lockTimer: 0, locking: false, lockResets: 0, softDrop: false, keySoft: false,
        clearing: null,            // { rows:[...], t }
        pendingGarbage: 0, garbageFlash: 0,
        ai: false, aiPlan: null, aiTimer: 0, aiSoftFall: false,
        pieceCount: 0, holdCount: 0, tetrisCount: 0,   // stats (also used by tests)
      };
    }
    function newBoard() { var b = new Array(ROWS * COLS); for (var i = 0; i < b.length; i++) b[i] = 0; return b; }
    function curCells(w) { return SHAPES[w.type].rot[w.rot]; }
    function curColor(w) { return SHAPES[w.type].color; }

    // ---- piece flow -------------------------------------------------------
    function refillQueue(w) {
      while (w.queue.length < 7) {
        if (!w.bag.length) w.bag = makeBag();
        w.queue.push(w.bag.shift());
      }
    }
    function dequeue(w) { refillQueue(w); return w.queue.shift(); }

    function spawnPiece(w, type) {
      var def = SHAPES[type];
      w.type = type; w.rot = 0; w.px = def.spawnX; w.py = def.spawnY;
      w.gravity = 0; w.lockTimer = 0; w.locking = false; w.lockResets = 0; w.softDrop = false;
      if (collides(w.board, def.rot[0], w.px, w.py)) setDead(w);   // can't even appear -> topped out
    }

    function spawnNext(w) {
      applyGarbage(w);
      if (w.dead) return;
      spawnPiece(w, dequeue(w));
      w.canHold = true;
      w.aiPlan = null;
    }

    // Pending garbage drops in just before the next piece appears: stack pushed
    // up, full rows except one hole column. If blocks would be shoved off the
    // top, that player is buried — topped out.
    function applyGarbage(w) {
      var g = w.pendingGarbage; w.pendingGarbage = 0;
      if (g <= 0) return;
      g = Math.min(g, ROWS);
      for (var y = 0; y < g; y++) {                 // anything in the top g rows = overflow
        for (var x = 0; x < COLS; x++) { if (w.board[y * COLS + x]) { setDead(w); return; } }
      }
      for (y = 0; y < ROWS - g; y++) {              // shift the stack up by g rows
        for (x = 0; x < COLS; x++) w.board[y * COLS + x] = w.board[(y + g) * COLS + x];
      }
      var hole = Math.floor(Math.random() * COLS);
      for (y = ROWS - g; y < ROWS; y++) {           // garbage rows at the bottom
        for (x = 0; x < COLS; x++) w.board[y * COLS + x] = (x === hole) ? 0 : GARBAGE;
      }
      w.garbageFlash = clock;
    }

    function award(w, n) {
      w.score += ([0, 100, 300, 500, 800][n] || 0) * w.level;
      w.lines += n;
      if (n >= 4) w.tetrisCount++;
      var lvl = 1 + Math.floor(w.lines / 10);
      if (lvl > w.level) w.level = lvl;
    }

    // Outgoing garbage first cancels your own incoming, the rest hits the rival.
    function sendGarbage(w, n) {
      if (numPlayers !== 2) return;
      var sent = GARBAGE_FOR[n] || 0;
      if (sent <= 0) return;
      var cancel = Math.min(sent, w.pendingGarbage);
      w.pendingGarbage -= cancel; sent -= cancel;
      if (sent > 0) otherWell(w).pendingGarbage += sent;
    }

    function lockPiece(w) {
      var cells = curCells(w), color = curColor(w), topped = false;
      for (var i = 0; i < cells.length; i++) {
        var y = w.py + cells[i][1];
        if (y < 0) { topped = true; break; }       // locked partly above the ceiling
      }
      stamp(w.board, cells, w.px, w.py, color);
      w.locking = false; w.lockTimer = 0; w.lockResets = 0;
      w.pieceCount++;
      if (topped) { setDead(w); return; }
      var rows = fullRows(w.board);
      if (rows.length) {
        award(w, rows.length);
        sendGarbage(w, rows.length);
        w.clearing = { rows: rows, t: 0 };
        w.type = null;                              // no active piece during the flash
      } else {
        spawnNext(w);
      }
    }

    function setDead(w) {
      if (w.dead) return;
      w.dead = true; w.type = null;
      if (numPlayers === 1) { result = { solo: true }; }
      else { result = { winner: otherWell(w).player }; }
      state = 'over';
      // Game's over: cancel every well's pending computer move so nothing keeps
      // "thinking"/playing after the result is decided.
      for (var i = 0; i < wells.length; i++) { wells[i].aiPlan = null; wells[i].aiTimer = 0; wells[i].aiSoftFall = false; }
    }

    // ---- piece actions (shared by touch, keyboard and the computer) -------
    function piecePlayable(w) { return state === 'playing' && !w.dead && w.type && !w.clearing; }

    function onPieceMoved(w) {                      // refresh the lock delay sensibly
      if (!collides(w.board, curCells(w), w.px, w.py + 1)) { w.locking = false; w.lockTimer = 0; }
      else if (w.locking && w.lockResets < MAX_LOCK_RESETS) { w.lockTimer = 0; w.lockResets++; }
    }
    function moveWell(w, d) {
      if (!piecePlayable(w)) return false;
      if (!collides(w.board, curCells(w), w.px + d, w.py)) { w.px += d; onPieceMoved(w); return true; }
      return false;
    }
    function rotateWell(w, dir) {
      if (!piecePlayable(w)) return false;
      var nr = (w.rot + (dir > 0 ? 1 : 3)) % 4, cells = SHAPES[w.type].rot[nr];
      for (var i = 0; i < KICKS.length; i++) {
        var kx = KICKS[i][0], ky = KICKS[i][1];
        if (!collides(w.board, cells, w.px + kx, w.py + ky)) {
          w.px += kx; w.py += ky; w.rot = nr; onPieceMoved(w); return true;
        }
      }
      return false;
    }
    function hardDrop(w) {
      if (!piecePlayable(w)) return;
      var dist = dropY(w.board, curCells(w), w.px, w.py) - w.py;
      if (dist > 0) { w.py += dist; w.score += dist * 2; }
      lockPiece(w);
    }
    function holdSwap(w) {
      if (!piecePlayable(w) || !w.canHold) return;
      var cur = w.type;
      if (w.hold === null) { w.hold = cur; spawnPiece(w, dequeue(w)); }
      else { var h = w.hold; w.hold = cur; spawnPiece(w, h); }
      w.canHold = false;
      w.holdCount++;
    }

    // ---- the computer -----------------------------------------------------
    // Is an I-piece within reach (current, held, or the next two)? When so, the
    // evaluation keeps a clean edge well open to bank a Tetris.
    function iNearFor(w) {
      return w.type === 'I' || w.hold === 'I' || w.queue[0] === 'I' || w.queue[1] === 'I';
    }

    // Decide the computer's move for the current piece: place it, or HOLD it and
    // play the other available piece instead. HOLD wins when the alternative
    // gives a clearly better board — e.g. the current piece fits poorly, or the
    // current piece is an I worth banking until a Tetris well is ready.
    function aiDecide(w) {
      var iNear = iNearFor(w);
      var curBest = bestPlacementAI(w.board, w.type, iNear) || { rot: w.rot, px: w.px, s: -Infinity };
      if (w.canHold) {
        var alt = w.hold !== null ? w.hold : w.queue[0];
        if (alt && alt !== w.type) {
          var altBest = bestPlacementAI(w.board, alt, iNear);
          if (altBest && altBest.s > curBest.s + AI_HOLD_MARGIN) return { hold: true };
        }
      }
      return curBest;
    }

    // Hard drop is the computer's instant slam — no human can race it. So it is
    // only used in solo autoplay and computer-vs-computer; against a person the
    // computer SOFT-DROPS instead (no slamming), giving them a fair pace.
    function aiHardDropAllowed(w) {
      return numPlayers !== 2 || otherWell(w).ai;
    }
    // The terminal action once a piece is positioned: slam it (if allowed), else
    // start a soft descent that gravity finishes and locks.
    function aiCommit(w) {
      if (aiHardDropAllowed(w)) { hardDrop(w); w.aiPlan = null; }
      else { w.aiSoftFall = true; }
    }

    function aiUpdate(w, dt) {
      if (state !== 'playing' || !piecePlayable(w)) return;   // never act once the game is over
      if (!w.aiPlan) { w.aiPlan = aiDecide(w); w.aiTimer = 0; w.aiSoftFall = false; }
      if (w.aiSoftFall) return;                               // lined up: let the soft drop finish it
      w.aiTimer += dt;
      if (w.aiTimer < AI_STEP) return;
      if (w.aiPlan.hold) { holdSwap(w); w.aiPlan = null; return; }   // swap, then re-plan the new piece
      w.aiTimer = 0;
      var plan = w.aiPlan;
      if (w.rot !== plan.rot) { if (!rotateWell(w, 1)) aiCommit(w); return; }   // line up the orientation
      if (w.px < plan.px) { if (!moveWell(w, 1)) aiCommit(w); return; }          // then slide across
      if (w.px > plan.px) { if (!moveWell(w, -1)) aiCommit(w); return; }
      aiCommit(w);                                            // positioned: slam, or soft-drop vs a human
    }

    // ---- per-frame update -------------------------------------------------
    function updateWell(w, dt) {
      if (w.dead) return;
      if (w.garbageFlash && clock - w.garbageFlash > 0.4) w.garbageFlash = 0;

      if (w.clearing) {                              // line-clear flash, then collapse
        w.clearing.t += dt;
        if (w.clearing.t >= CLEAR_TIME) {
          w.board = clearRows(w.board, w.clearing.rows);
          w.clearing = null;
          spawnNext(w);
        }
        return;
      }
      if (!w.type) { spawnNext(w); if (w.dead || !w.type) return; }

      if (w.ai) aiUpdate(w, dt);
      if (!piecePlayable(w)) return;                 // AI may have locked the piece

      var interval = w.softDrop ? gravityInterval(w.level) / SOFT_MULT : gravityInterval(w.level);
      if (w.aiSoftFall && interval > AI_SOFT_INTERVAL) interval = AI_SOFT_INTERVAL;   // brisk, level-independent
      w.gravity += dt;
      while (w.gravity >= interval) {
        w.gravity -= interval;
        if (!collides(w.board, curCells(w), w.px, w.py + 1)) {
          w.py++;
          if (w.softDrop) w.score += 1;
          w.locking = false; w.lockTimer = 0;
        } else { w.locking = true; break; }
      }
      if (w.locking) {
        w.lockTimer += dt;
        if (w.lockTimer >= LOCK_DELAY) lockPiece(w);
      }
    }

    function update(dt) {
      if (state !== 'playing' || paused) return;   // PAUSE freezes gravity, AI and input
      // soft drop = any finger dragging down on this well, OR its held key
      for (var i = 0; i < wells.length; i++) wells[i].softDrop = wells[i].keySoft;
      for (var id in ptrs) {
        var p = ptrs[id];
        if (p.soft && wells[p.well] && !wells[p.well].ai) wells[p.well].softDrop = true;
      }
      // a computer well drives its own descent: soft drop only when it is letting
      // a positioned piece fall (vs a human); otherwise normal gravity.
      for (i = 0; i < wells.length; i++) { if (wells[i].ai) wells[i].softDrop = !!wells[i].aiSoftFall; updateWell(wells[i], dt); }
    }

    // ---- flow -------------------------------------------------------------
    function startGame(n) {
      numPlayers = n;
      wells = [];
      for (var i = 0; i < n; i++) { var w = makeWell(i + 1); refillQueue(w); spawnNext(w); wells.push(w); }
      result = null;
      paused = false;
      state = 'playing';
      relayout();
    }
    function restart() { startGame(numPlayers); }
    function toMenu() { state = 'menu'; paused = false; wells = []; result = null; relayout(); }
    function togglePause() { if (state === 'playing') paused = !paused; }
    function toggleAI(w) { w.ai = !w.ai; w.aiPlan = null; }
    function finishToCatalogue() { window.location.href = '../../index.html'; }

    // ===========================================================================
    // LAYOUT — size the well(s) to the viewport and place the chrome around them.
    // Computed fresh on every resize; chrome rects are recomputed each frame from
    // the well rects so drawing and hit-testing always agree.
    // ===========================================================================
    function relayout() { layout({ width: vw || window.innerWidth, height: vh || window.innerHeight }); }

    function layout(info) {
      var dpr = window.devicePixelRatio || 1;
      vw = info.width; vh = info.height;
      canvas.style.width = vw + 'px';
      canvas.style.height = vh + 'px';
      canvas.width = Math.round(vw * dpr);
      canvas.height = Math.round(vh * dpr);
      drawScale = dpr;

      var pad = clamp(Math.min(vw, vh) * 0.025, 6, 26);
      var n = (state === 'playing' || state === 'over') ? numPlayers : 1;
      var landscape = vw >= vh;
      var HC = 5;                                        // side-HUD column width, in cells
      wellRects = [];

      if (n === 2 && landscape) {
        // 2P landscape: P1 HUD | board | board | P2 HUD. Boards maximised to the
        // canvas height (HUD lives in the outer margins, no top band to steal it).
        hudMode = 'sideEach';
        var cH2 = (vh - 2 * pad) / ROWS;
        var cW2 = (vw - 2 * pad - pad) / (2 * COLS + 2 * HC);
        cell = Math.max(8, Math.min(cH2, cW2));
        var wW = cell * COLS, wH = cell * ROWS, hudW = cell * HC, mid = pad;
        var totalW = 2 * hudW + 2 * wW + mid;
        var left = (vw - totalW) / 2, top = (vh - wH) / 2;
        var b1x = left + hudW, b2x = b1x + wW + mid;
        wellRects.push({ x: b1x, y: top, w: wW, h: wH });
        wellRects.push({ x: b2x, y: top, w: wW, h: wH });
      } else if (n === 2) {
        // 2P portrait: two wells side-by-side, each with a HUD band above.
        hudMode = 'topBand';
        var HUD = 3.4;                                   // band height in cells
        var cH = (vh - 2 * pad) / (ROWS + HUD);
        var cW = (vw - 3 * pad) / (2 * COLS);
        cell = Math.max(8, Math.min(cH, cW));
        var wWb = cell * COLS, wHb = cell * ROWS, hud = cell * HUD;
        var totalWb = 2 * wWb + pad, totalHb = wHb + hud;
        var leftb = (vw - totalWb) / 2, topb = (vh - totalHb) / 2 + hud;
        wellRects.push({ x: leftb, y: topb, w: wWb, h: wHb });
        wellRects.push({ x: leftb + wWb + pad, y: topb, w: wWb, h: wHb });
      } else if (landscape) {
        // 1P landscape: board centred & maximised to height; ALL HUD in the left
        // margin, the right margin left empty.
        hudMode = 'leftStack';
        var cHl = (vh - 2 * pad) / ROWS;
        var cWl = (vw - 2 * pad) / (COLS + 2 * HC);      // guarantee the left margin holds the HUD
        cell = Math.max(8, Math.min(cHl, cWl));
        var wWl = cell * COLS, wHl = cell * ROWS;
        wellRects.push({ x: (vw - wWl) / 2, y: (vh - wHl) / 2, w: wWl, h: wHl });
      } else {
        // 1P portrait: well fills the height, HUD band across the top.
        hudMode = 'topBand';
        var HUD1 = 4.4;
        var cHp = (vh - 2 * pad) / (ROWS + HUD1);
        var cWp = (vw - 2 * pad) / COLS;
        cell = Math.max(8, Math.min(cHp, cWp));
        var wWp = cell * COLS, wHp = cell * ROWS, hudp = cell * HUD1;
        var topP = (vh - wHp - hudp) / 2 + hudp;
        wellRects.push({ x: (vw - wWp) / 2, y: topP, w: wWp, h: wHp });
      }
    }

    // Chrome rects (FINISH + per-well HUD boxes), derived from the well rects.
    // FINISH sits in the top-LEFT corner (never over the centred well); any HUD
    // panel that falls under it is dropped below `topClear` so they don't collide.
    function chrome() {
      var u = Math.min(vw, vh);
      var bw = clamp(u * 0.13, 60, 132), bh = clamp(u * 0.05, 28, 46);
      var m = clamp(u * 0.018, 6, 20), gap = clamp(u * 0.02, 6, 16);
      var finish = { x: m, y: m, w: bw, h: bh };
      var c = { finish: finish, pause: null, players: [] };
      // PAUSE sits just right of FINISH, only while a game is in progress.
      var bar = { x: finish.x, y: finish.y, w: finish.w, h: finish.h };
      if (state === 'playing') {
        c.pause = { x: finish.x + finish.w + gap, y: finish.y, w: clamp(u * 0.135, 64, 138), h: bh };
        bar.w = (c.pause.x + c.pause.w) - bar.x;       // union of the two buttons
      }
      var topClear = bar.y + bar.h + gap;              // HUD content drops below the button row
      for (var i = 0; i < wellRects.length; i++) c.players.push(hudFor(wellRects[i], i, bar, topClear));
      return c;
    }

    // Lay out one player's HUD: robot toggle, P# label, score/lines/level, NEXT
    // queue and HOLD. 'topBand' draws a compact band above the well; 'leftStack'
    // (1P landscape) and 'sideEach' (2P landscape) draw a vertical column in a
    // side margin — P1 on the left, P2 on the right.
    function hudFor(r, i, topBar, topClear) {
      var unit = Math.min(vw, vh);
      function underBar(x0, x1) { return topBar && x0 < topBar.x + topBar.w && x1 > topBar.x; }

      if (hudMode === 'topBand') {
        var band = { x: r.x, y: 0, w: r.w, h: r.y };
        var m = clamp(unit * 0.015, 4, 12);
        var top = clamp(band.h * 0.06, 4, 18);
        if (underBar(band.x, band.x + band.w)) top = Math.max(top, topClear || 0);
        var iconS = clamp(cell * 1.5, 26, 64);
        var miniC = clamp(cell * 0.62, 9, 26);            // cell size of NEXT / HOLD minis
        var nextW = miniC * 4.4;
        return {
          compactStats: true, band: band,
          robot: { x: band.x + m, y: top, w: iconS, h: iconS },
          label: { x: band.x + m + iconS + m * 0.8, y: top, h: iconS },
          stats: { x: band.x + m, y: top + iconS + m * 0.4, w: band.w - 2 * m },
          hold: { x: band.x + band.w * 0.5 - nextW - m, y: top, w: nextW, miniC: miniC },
          next: [{ x: band.x + band.w - nextW - m, y: top, w: nextW, miniC: miniC }],
          nextCount: 1, miniC: miniC,
        };
      }

      // Column layouts: a vertical stack in a side margin, below the button bar.
      var pm = clamp(unit * 0.02, 6, 20);
      var colX, colW;
      if (hudMode === 'sideEach') {
        var hudW = cell * 5;
        colX = (i === 0) ? r.x - hudW + pm : r.x + r.w + pm;   // P1 left of board, P2 right of board
        colW = hudW - 2 * pm;
      } else {                                                 // leftStack: the whole left margin
        colX = pm;
        colW = r.x - 2 * pm;
      }
      return columnHud(colX, colW, topClear || pm, unit, pm);
    }

    // A vertical HUD column: robot + P#, stats, HOLD, three NEXT previews.
    function columnHud(colX, colW, top, unit, pm) {
      var iconL = clamp(cell * 1.5, 28, 64);
      var miniC = clamp(cell * 0.62, 10, 26);
      var st = clamp(unit * 0.028, 11, 22);
      var boxW = Math.min(colW, miniC * 4.4);
      var y = top;
      var robot = { x: colX, y: y, w: iconL, h: iconL };
      var labelBox = { x: colX + iconL + pm * 0.6, y: y, h: iconL };
      y += iconL + pm;
      var stats = { x: colX, y: y, w: colW };
      y += st * 4.8 + pm;
      var hold = { x: colX, y: y + miniC * 1.3, w: boxW, miniC: miniC };
      y = hold.y + miniC * 3 + pm;
      var nexts = [], n0y = y + miniC * 1.3;
      for (var k = 0; k < 3; k++) nexts.push({ x: colX, y: n0y + k * (miniC * 3 + miniC * 0.45), w: boxW, miniC: miniC });
      return {
        compactStats: false, band: null,
        robot: robot, label: labelBox, stats: stats,
        hold: hold, next: nexts, nextCount: 3, miniC: miniC,
      };
    }

    // ===========================================================================
    // INPUT — gestures per finger (assigned to the well it begins over) plus
    // desktop keyboard. FINISH / robot toggles / menu buttons are tapped.
    // ===========================================================================
    var TAP_MOVE = 0.5;     // *cell: total motion under this on release = a tap
    var FLICK_V = 18;       // *cell/s: downward speed that counts as a hard-drop flick

    function inRect(x, y, b) { return b && x >= b.x && x <= b.x + b.w && y >= b.y && y <= b.y + b.h; }
    function robotRect(p) { return p.robot; }
    function holdBoxOf(p) { return { x: p.hold.x, y: p.hold.y, w: p.hold.w || (p.miniC * 4.2), h: p.miniC * 3 }; }

    function wellForStart(startNx) { return numPlayers === 2 ? (startNx < 0.5 ? 0 : 1) : 0; }

    function menuButtons() {
      var unit = Math.min(vw, vh);
      var bw = clamp(unit * 0.5, 180, 360), bh = clamp(unit * 0.13, 56, 110);
      var gap = clamp(unit * 0.05, 14, 36), cx = vw / 2, cy = vh * 0.52;
      return {
        one: { x: cx - bw / 2, y: cy, w: bw, h: bh },
        two: { x: cx - bw / 2, y: cy + bh + gap, w: bw, h: bh },
      };
    }
    function overButtons() {
      var unit = Math.min(vw, vh);
      var bw = clamp(unit * 0.34, 130, 240), bh = clamp(unit * 0.08, 42, 72);
      var gap = clamp(unit * 0.04, 12, 28), cx = vw / 2, cy = vh * 0.6;
      return {
        again: { x: cx - bw - gap / 2, y: cy, w: bw, h: bh },
        menu: { x: cx + gap / 2, y: cy, w: bw, h: bh },
      };
    }

    NG.createTouch(canvas, {
      onDown: function (pt) {
        ptrs[pt.id] = {
          well: wellForStart(pt.startNx), sx: pt.x, sy: pt.y, lx: pt.x, ly: pt.y,
          lt: now(), appliedCol: 0, moved: false, soft: false, done: false,
        };
      },
      onMove: function (pt) {
        var info = ptrs[pt.id];
        if (!info || info.done) return;
        var dx = pt.x - info.sx, dy = pt.y - info.sy;
        if (Math.abs(dx) > cell * TAP_MOVE || Math.abs(dy) > cell * TAP_MOVE) info.moved = true;
        if (state !== 'playing' || paused) return;
        var w = wells[info.well];
        if (!w || w.dead || w.ai || !w.type) return;

        // horizontal: keep the piece under the finger, column by column
        var desired = Math.round(dx / cell);
        while (info.appliedCol < desired && moveWell(w, 1)) info.appliedCol++;
        while (info.appliedCol > desired && moveWell(w, -1)) info.appliedCol--;

        // vertical: hold below the start = soft drop; a fast flick = hard drop
        info.soft = (dy > cell * 0.55 && dy > Math.abs(dx));
        var t = now(), ddt = (t - info.lt) / 1000;
        var vy = ddt > 0 ? (pt.y - info.ly) / ddt : 0;
        if (dy > cell * 1.4 && vy > FLICK_V * cell && dy > Math.abs(dx)) {
          hardDrop(w); info.done = true; info.soft = false;
        }
        info.lx = pt.x; info.ly = pt.y; info.lt = t;
      },
      onUp: function (pt) {
        var info = ptrs[pt.id];
        delete ptrs[pt.id];
        if (!info) return;
        var tap = !info.moved;

        if (state === 'menu') {
          if (!tap) return;
          var mb = menuButtons();
          if (inRect(pt.x, pt.y, chrome().finish)) { finishToCatalogue(); return; }
          if (inRect(pt.x, pt.y, mb.one)) { startGame(1); return; }
          if (inRect(pt.x, pt.y, mb.two)) { startGame(2); return; }
          return;
        }

        if (tap && inRect(pt.x, pt.y, chrome().finish)) { finishToCatalogue(); return; }

        if (state === 'over') {
          if (!tap) return;
          var ob = overButtons();
          if (inRect(pt.x, pt.y, ob.menu)) { toMenu(); return; }
          restart(); return;                       // anywhere else replays the same mode
        }

        // playing: PAUSE toggles; while paused, a tap anywhere resumes
        var cl = chrome();
        if (tap && cl.pause && inRect(pt.x, pt.y, cl.pause)) { togglePause(); return; }
        if (paused) { if (tap) paused = false; return; }
        // robot toggles + HOLD-box taps first, then resolve the gesture
        for (var i = 0; i < cl.players.length; i++) {
          if (!tap) break;
          if (inRect(pt.x, pt.y, robotRect(cl.players[i]))) { toggleAI(wells[i]); return; }
          if (inRect(pt.x, pt.y, holdBoxOf(cl.players[i])) && wells[i] && !wells[i].ai) { holdSwap(wells[i]); return; }
        }
        var w = wells[info.well];
        if (!w || w.dead || w.ai || info.done || !w.type) return;
        var dx = pt.x - info.sx, dy = pt.y - info.sy;
        if (tap) rotateWell(w, 1);
        else if (dy < -cell * 1.6 && Math.abs(dy) > Math.abs(dx)) holdSwap(w);   // swipe up = hold
        else if (dy > cell * 1.6 && Math.abs(dy) > Math.abs(dx)) hardDrop(w);    // slow swipe down = drop
      },
    });

    // One immediate downward step (the "extra step" on a soft-drop key press), so
    // tapping Down repeatedly steps the piece down a row at a time.
    function softStep(w) {
      if (!w || w.ai || !piecePlayable(w)) return;
      if (!collides(w.board, curCells(w), w.px, w.py + 1)) {
        w.py++; w.score += 1; w.gravity = 0; w.locking = false; w.lockTimer = 0;
      }
    }

    // Keyboard: desktop-development convenience only (the game never requires it).
    // P1 (left) = WASD + Q hard-drop + E hold; P2 (right) = arrows + Enter
    // hard-drop + / hold. In 1P, BOTH clusters drive P1. Soft drop (S / Down):
    // held = 2x speed; each fresh press also steps down one row.
    window.addEventListener('keydown', function (ev) {
      var k = (ev.key || '').toLowerCase();
      if (state === 'menu') {
        if (k === '1') { startGame(1); ev.preventDefault(); }
        else if (k === '2') { startGame(2); ev.preventDefault(); }
        return;
      }
      if (state === 'over') {
        if (k === 'enter' || k === ' ' || k === 'spacebar') { restart(); ev.preventDefault(); }
        else if (k === 'm' || k === 'escape') { toMenu(); ev.preventDefault(); }
        return;
      }
      if (k === 'p') { togglePause(); ev.preventDefault(); return; }
      if (paused) return;                          // controls are inert while paused
      var p1 = wells[0];
      var arrow = numPlayers === 1 ? wells[0] : wells[1];   // arrows drive P1 (1P) or P2 (2P)
      var used = true;
      switch (k) {
        // P1 cluster: WASD (+ X rotate, Z rotate-ccw, Q hard-drop, E/C hold)
        case 'a': moveWell(p1, -1); break;
        case 'd': moveWell(p1, 1); break;
        case 'w': case 'x': rotateWell(p1, 1); break;
        case 'z': rotateWell(p1, -1); break;
        case 's': if (p1) { p1.keySoft = true; } if (!ev.repeat) softStep(p1); break;
        case 'q': hardDrop(p1); break;
        case 'e': case 'c': holdSwap(p1); break;
        case ' ': case 'spacebar': hardDrop(p1); break;
        // arrows cluster: P2 in 2P, P1 in 1P
        case 'arrowleft': moveWell(arrow, -1); break;
        case 'arrowright': moveWell(arrow, 1); break;
        case 'arrowup': rotateWell(arrow, 1); break;
        case 'arrowdown': if (arrow) { arrow.keySoft = true; } if (!ev.repeat) softStep(arrow); break;
        case 'enter': hardDrop(arrow); break;
        case '/': holdSwap(arrow); break;
        default: used = false;
      }
      if (used) ev.preventDefault();
    });
    window.addEventListener('keyup', function (ev) {
      var k = (ev.key || '').toLowerCase();
      var arrow = numPlayers === 1 ? wells[0] : wells[1];
      if (k === 's' && wells[0]) wells[0].keySoft = false;
      if (k === 'arrowdown' && arrow) arrow.keySoft = false;
    });

    NG.onExit(finishToCatalogue);

    // ===========================================================================
    // RENDERING
    // ===========================================================================
    function rrect(x, y, w, h, rad) {
      rad = Math.min(rad, w / 2, h / 2);
      ctx.beginPath();
      ctx.moveTo(x + rad, y);
      ctx.arcTo(x + w, y, x + w, y + h, rad);
      ctx.arcTo(x + w, y + h, x, y + h, rad);
      ctx.arcTo(x, y + h, x, y, rad);
      ctx.arcTo(x, y, x + w, y, rad);
      ctx.closePath();
    }

    // A beveled mini-block: flat fill, a light strip on top and a dark strip on
    // the bottom so the stack reads as solid tiles (cheap — no per-cell shadow).
    function block(x, y, s, color, alpha) {
      var p = Math.max(1, s * 0.07), is = s - 2 * p;
      ctx.globalAlpha = alpha == null ? 1 : alpha;
      ctx.fillStyle = color; rrect(x + p, y + p, is, is, s * 0.2); ctx.fill();
      ctx.fillStyle = 'rgba(255,255,255,0.26)'; rrect(x + p, y + p, is, is * 0.36, s * 0.2); ctx.fill();
      ctx.fillStyle = 'rgba(0,0,0,0.24)'; rrect(x + p, y + p + is * 0.74, is, is * 0.26, s * 0.18); ctx.fill();
      ctx.globalAlpha = 1;
    }
    function ghostBlock(x, y, s, color) {
      var p = Math.max(1, s * 0.07);
      ctx.globalAlpha = 0.22; ctx.strokeStyle = color; ctx.lineWidth = Math.max(1, s * 0.08);
      rrect(x + p, y + p, s - 2 * p, s - 2 * p, s * 0.2); ctx.stroke(); ctx.globalAlpha = 1;
    }

    function drawWell(w, r) {
      ctx.fillStyle = WELL_BG;
      rrect(r.x - cell * 0.18, r.y - cell * 0.18, r.w + cell * 0.36, r.h + cell * 0.36, cell * 0.3);
      ctx.fill();

      ctx.strokeStyle = GRID; ctx.lineWidth = 1;          // faint grid
      ctx.beginPath();
      for (var gx = 1; gx < COLS; gx++) { ctx.moveTo(r.x + gx * cell, r.y); ctx.lineTo(r.x + gx * cell, r.y + r.h); }
      for (var gy = 1; gy < ROWS; gy++) { ctx.moveTo(r.x, r.y + gy * cell); ctx.lineTo(r.x + r.w, r.y + gy * cell); }
      ctx.stroke();

      // locked stack
      for (var y = 0; y < ROWS; y++) for (var x = 0; x < COLS; x++) {
        var v = w.board[y * COLS + x];
        if (v) block(r.x + x * cell, r.y + y * cell, cell, v);
      }

      // line-clear flash: bright wash over the rows about to vanish
      if (w.clearing) {
        var f = 0.4 + 0.6 * Math.abs(Math.sin(clock * 30));
        ctx.globalAlpha = f; ctx.fillStyle = '#ffffff';
        for (var i = 0; i < w.clearing.rows.length; i++) {
          ctx.fillRect(r.x, r.y + w.clearing.rows[i] * cell, r.w, cell);
        }
        ctx.globalAlpha = 1;
      }

      if (piecePlayable(w)) {
        var cells = curCells(w), color = curColor(w);
        var gyp = dropY(w.board, cells, w.px, w.py);       // ghost
        for (i = 0; i < cells.length; i++) {
          var cy = gyp + cells[i][1];
          if (cy >= 0) ghostBlock(r.x + (w.px + cells[i][0]) * cell, r.y + cy * cell, cell, color);
        }
        for (i = 0; i < cells.length; i++) {               // active piece
          var ay = w.py + cells[i][1];
          if (ay >= 0) block(r.x + (w.px + cells[i][0]) * cell, r.y + ay * cell, cell, color);
        }
      }

      // incoming-garbage meter up the inner edge: a red tick per pending row
      if (numPlayers === 2 && w.pendingGarbage > 0) {
        var inner = (w === wells[0]);
        var mx = inner ? r.x + r.w + cell * 0.22 : r.x - cell * 0.22 - cell * 0.3;
        var pulse = 0.55 + 0.45 * Math.abs(Math.sin(clock * 6));
        ctx.globalAlpha = pulse; ctx.fillStyle = '#ff5d6c';
        for (i = 0; i < Math.min(w.pendingGarbage, ROWS); i++) {
          ctx.fillRect(mx, r.y + r.h - (i + 1) * cell + cell * 0.12, cell * 0.3, cell * 0.76);
        }
        ctx.globalAlpha = 1;
      }

      ctx.strokeStyle = w.dead ? '#3a2730' : DIM;          // border
      ctx.lineWidth = Math.max(2, cell * 0.09);
      rrect(r.x - cell * 0.18, r.y - cell * 0.18, r.w + cell * 0.36, r.h + cell * 0.36, cell * 0.3);
      ctx.stroke();
    }

    // Draw a piece centred in a small box (NEXT / HOLD previews).
    function drawMini(type, cx, cy, mc, dim) {
      if (!type) return;
      var def = SHAPES[type], cells = def.rot[0];
      var minx = minOf(cells, 0), miny = minOf(cells, 1);
      var maxx = -Infinity, maxy = -Infinity;
      for (var i = 0; i < cells.length; i++) { maxx = Math.max(maxx, cells[i][0]); maxy = Math.max(maxy, cells[i][1]); }
      var pw = (maxx - minx + 1) * mc, ph = (maxy - miny + 1) * mc;
      var ox = cx - pw / 2 - minx * mc, oy = cy - ph / 2 - miny * mc;
      for (i = 0; i < cells.length; i++) {
        block(ox + cells[i][0] * mc, oy + cells[i][1] * mc, mc, def.color, dim ? 0.55 : 1);
      }
    }

    function drawRobot(b, color, active) {
      var cx = b.x + b.w / 2, cy = b.y + b.h / 2, s = b.w * 0.4;
      ctx.globalAlpha = active ? 1 : 0.55;
      ctx.lineWidth = Math.max(1.5, s * 0.16); ctx.strokeStyle = color;
      ctx.beginPath(); ctx.moveTo(cx, cy - s * 0.7); ctx.lineTo(cx, cy - s * 1.15); ctx.stroke();   // antenna
      ctx.fillStyle = color;
      ctx.beginPath(); ctx.arc(cx, cy - s * 1.25, Math.max(1.5, s * 0.16), 0, Math.PI * 2); ctx.fill();
      var hw = s * 1.5, hh = s * 1.25, hx = cx - hw / 2, hy = cy - hh * 0.4;
      ctx.fillStyle = active ? color : 'rgba(255,255,255,0.05)';
      rrect(hx, hy, hw, hh, s * 0.3); ctx.fill(); ctx.stroke();
      var face = active ? WELL_BG : color;
      ctx.fillStyle = face;
      ctx.beginPath(); ctx.arc(cx - s * 0.4, cy + s * 0.02, s * 0.2, 0, Math.PI * 2); ctx.fill();
      ctx.beginPath(); ctx.arc(cx + s * 0.4, cy + s * 0.02, s * 0.2, 0, Math.PI * 2); ctx.fill();
      ctx.strokeStyle = face; ctx.lineWidth = Math.max(1, s * 0.13);
      ctx.beginPath(); ctx.moveTo(cx - s * 0.32, cy + s * 0.46); ctx.lineTo(cx + s * 0.32, cy + s * 0.46); ctx.stroke();
      ctx.globalAlpha = 1;
    }

    function label(txt, x, y, size, color, align, baseline) {
      ctx.fillStyle = color;
      ctx.font = 'bold ' + size.toFixed(0) + 'px "Courier New", monospace';
      ctx.textAlign = align || 'left'; ctx.textBaseline = baseline || 'top';
      ctx.fillText(txt, x, y);
    }

    function drawHud(w, p) {
      var color = w.player === 1 ? FG : '#ffcf4d';
      var unit = Math.min(vw, vh);
      drawRobot(p.robot, color, w.ai);
      var lblSize = clamp(p.robot.h * 0.42, 12, 30);
      label('P' + w.player, p.label.x, p.label.y + p.robot.h / 2 - lblSize * 0.6, lblSize, color);
      var role = w.ai ? 'CPU' : 'YOU';
      label(role, p.label.x, p.label.y + p.robot.h / 2 + lblSize * 0.55, lblSize * 0.7, w.ai ? color : MUTED);

      // stats
      var st = clamp(unit * 0.028, 11, 22);
      var sx = p.stats.x, sy = p.stats.y;
      if (p.compactStats) {
        label('SCORE ' + w.score + '   LV ' + w.level + '   LN ' + w.lines, sx, sy, st, INK);
      } else {
        label('SCORE', sx, sy, st * 0.78, MUTED); label(String(w.score), sx, sy + st * 0.95, st * 1.15, INK);
        label('LEVEL ' + w.level, sx, sy + st * 2.5, st * 0.92, INK);
        label('LINES ' + w.lines, sx, sy + st * 3.6, st * 0.92, INK);
      }

      // HOLD
      var hl = clamp(p.miniC * 0.7, 9, 18);
      label('HOLD', p.hold.x, p.hold.y - hl * 1.2, hl, MUTED);
      var hb = holdBoxOf(p);
      ctx.strokeStyle = 'rgba(77,255,136,0.2)'; ctx.lineWidth = 1;
      rrect(hb.x, hb.y, hb.w, hb.h, p.miniC * 0.4); ctx.stroke();
      if (w.hold) drawMini(w.hold, hb.x + hb.w / 2, hb.y + hb.h / 2, p.miniC, !w.canHold);

      // NEXT
      label('NEXT', p.next[0].x, p.next[0].y - hl * 1.2, hl, MUTED);
      for (var i = 0; i < p.nextCount && i < w.queue.length; i++) {
        var nb = p.next[i];
        var box = { x: nb.x, y: nb.y, w: nb.w || (nb.miniC * 4.2), h: p.miniC * 3 };
        ctx.strokeStyle = 'rgba(77,255,136,0.16)'; ctx.lineWidth = 1;
        rrect(box.x, box.y, box.w, box.h, p.miniC * 0.4); ctx.stroke();
        drawMini(w.queue[i], box.x + box.w / 2, box.y + box.h / 2, p.miniC, i > 0);
      }
    }

    function drawButton(b, txt, accent, big) {
      ctx.lineWidth = 1.5; ctx.strokeStyle = accent || FG;
      ctx.fillStyle = 'rgba(0,0,0,0.45)';
      rrect(b.x, b.y, b.w, b.h, Math.min(b.w, b.h) * 0.22); ctx.fill(); ctx.stroke();
      label(txt, b.x + b.w / 2, b.y + b.h / 2, b.h * (big ? 0.42 : 0.4), accent || FG, 'center', 'middle');
    }

    function drawMenu() {
      var unit = Math.min(vw, vh), cx = vw / 2;
      ctx.save();
      // title
      ctx.fillStyle = FG; ctx.shadowColor = FG; ctx.shadowBlur = unit * 0.03;
      label('TETRA DROP', cx, vh * 0.26, unit * 0.16, FG, 'center', 'middle');
      ctx.shadowBlur = 0;
      label('FALLING BLOCKS · TOUCH ONLY', cx, vh * 0.36, unit * 0.03, MUTED, 'center', 'middle');
      var mb = menuButtons();
      drawButton(mb.one, '1 PLAYER', FG, true);
      drawButton(mb.two, '2 PLAYERS', '#ffcf4d', true);
      // sit the hint a comfortable margin below the last button (anchored to it,
      // not a fixed fraction of the height, so it never rides up onto the box on
      // short landscape/squarish screens), clamped to stay on-screen.
      var hintY = Math.min(mb.two.y + mb.two.h + unit * 0.08, vh - unit * 0.05);
      label('TAP A ROBOT IN-GAME TO HAND A WELL TO THE COMPUTER',
        cx, hintY, unit * 0.026, MUTED, 'center', 'middle');
      ctx.restore();
    }

    function drawOver() {
      ctx.fillStyle = 'rgba(0,0,0,0.62)'; ctx.fillRect(0, 0, vw, vh);
      var unit = Math.min(vw, vh), cx = vw / 2;
      var title, tcol = FG;
      if (result && result.winner) { title = 'PLAYER ' + result.winner + ' WINS'; tcol = result.winner === 1 ? FG : '#ffcf4d'; }
      else { title = 'GAME OVER'; }
      ctx.fillStyle = tcol; ctx.shadowColor = tcol; ctx.shadowBlur = unit * 0.025;
      label(title, cx, vh * 0.34, unit * 0.1, tcol, 'center', 'middle');
      ctx.shadowBlur = 0;
      if (numPlayers === 1 && wells[0]) {
        label('SCORE ' + wells[0].score + '   LINES ' + wells[0].lines,
          cx, vh * 0.45, unit * 0.04, INK, 'center', 'middle');
      }
      var ob = overButtons();
      drawButton(ob.again, 'PLAY AGAIN', FG);
      drawButton(ob.menu, 'MAIN MENU', MUTED);
    }

    function draw() {
      ctx.setTransform(1, 0, 0, 1, 0, 0);
      ctx.clearRect(0, 0, canvas.width, canvas.height);
      ctx.setTransform(drawScale, 0, 0, drawScale, 0, 0);

      if (state === 'menu') { drawMenu(); drawButton(chrome().finish, 'FINISH', FG); return; }

      var cl = chrome();
      for (var i = 0; i < wells.length; i++) { drawWell(wells[i], wellRects[i]); drawHud(wells[i], cl.players[i]); }
      drawButton(cl.finish, 'FINISH', FG);
      if (cl.pause) drawButton(cl.pause, paused ? 'RESUME' : 'PAUSE', paused ? '#ffcf4d' : FG);
      if (paused) drawPaused();
      if (state === 'over') drawOver();
    }

    function drawPaused() {
      ctx.fillStyle = 'rgba(0,0,0,0.6)'; ctx.fillRect(0, 0, vw, vh);
      var unit = Math.min(vw, vh), cx = vw / 2;
      ctx.fillStyle = FG; ctx.shadowColor = FG; ctx.shadowBlur = unit * 0.025;
      label('PAUSED', cx, vh * 0.44, unit * 0.11, FG, 'center', 'middle');
      ctx.shadowBlur = 0;
      var pulse = 0.55 + 0.45 * Math.abs(Math.sin(clock * 2.2));
      ctx.globalAlpha = pulse;
      label('TAP TO RESUME', cx, vh * 0.54, unit * 0.04, INK, 'center', 'middle');
      ctx.globalAlpha = 1;
    }

    // ---- boot -------------------------------------------------------------
    NG.onResize(layout);

    var last = 0;
    function loop(t) {
      if (!last) last = t;
      var dt = Math.min((t - last) / 1000, 1 / 30);
      last = t;
      clock += dt;
      update(dt);
      draw();
      window.requestAnimationFrame(loop);
    }
    window.requestAnimationFrame(loop);

    // Expose the pure core for the headless test harness (no-op in the browser).
    if (window.__TETRIS_TEST__) {
      window.__tetris = {
        COLS: COLS, ROWS: ROWS, SHAPES: SHAPES, TYPES: TYPES,
        collides: collides, dropY: dropY, stamp: stamp, fullRows: fullRows,
        clearRows: clearRows, boardMetrics: boardMetrics,
        evaluatePlacement: evaluatePlacement, bestPlacement: bestPlacement,
        bestPlacementAI: bestPlacementAI, aiPlacementValue: aiPlacementValue, edgeWellDepth: edgeWellDepth,
        newBoard: newBoard,
        // live game accessors, so the harness can drive real flows + the computer
        game: {
          start: startGame, toMenu: toMenu, restart: restart,
          state: function () { return state; },
          result: function () { return result; },
          wells: function () { return wells; },
          chrome: function () { return chrome(); },
          wellRects: function () { return wellRects; },
          setAI: function (i, on) { if (wells[i]) { wells[i].ai = on; wells[i].aiPlan = null; } },
        },
      };
    }
  });
})();
